import { Hero } from "@/components/Hero";
import { Slider } from "@/components/Slider";
import Head from "next/head";
import { SliderImages } from "@/components/SliderImages";
export default function Home() {
  return (
    <>
      <Head>
        <title>Photo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        heading="Nature from different perseptive"
        message="Nature from all over the world"
      />
      <Slider SliderImages={SliderImages} />
    </>
  );
}
